### ISSUE TITLE
Doesn't properly stream logs

### ISSUE THREAD

**Issue by aegershman** [aegershman/pcf-pipelines-selective-deploy#1]
Once it runs "apply changes", the logs don't properly stream

https://opsman-dev-api-docs.cfapps.io/#getting-a-list-of-recent-install-events

**Comment by aegershman** [comment]
Raising this in priority because it somewhat blocks #13 ; if this doesn't stream the logs properly, it will simply return from the task as "success" && release the lock. Then another job will aquire the lock && fail because "an installation is in progress".

We need to get this to stream the logs for the entirety of the "apply-changes", or else it will release the lock too soon

**Comment by aegershman** [comment]
Successfully re-attaches to the running job. Nice!

```
X-Xss-Protection: 1; mode=block
{
  "install": {
    "id": 82
  }
}
found already running installation...re-attaching (Installation ID: 82, Started: Fri May 11 06:52:37 UTC 2018)
{"type": "step_started", "id": "bosh_product.deploying"}
===== 2018-05-11 06:52:37 UTC Running "/usr/local/bin/bosh --no-color --non-interactive --tty create-env /var/tempest/workspaces/default/deployments/bosh.yml"
Deployment manifest: '/var/tempest/workspaces/default/deployments/bosh.yml'
Deployment state: '/var/tempest/workspaces/default/deployments/bosh-state.json'
```

**Comment by xyloman** [comment]
Nice good work I this improvement

**Comment by aegershman** [comment]
I, too, this improvement
